# Generated by Django 2.2 on 2021-09-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0002_vacina_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='name',
            field=models.CharField(default='Name', max_length=100, verbose_name='Nome'),
        ),
    ]
