# Generated by Django 2.2 on 2021-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0003_auto_20210901_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='lastName',
            field=models.CharField(default='Name', max_length=100, verbose_name='lastName'),
        ),
    ]
