# Generated by Django 2.2 on 2021-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0004_auto_20210901_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='lastName',
        ),
        migrations.AddField(
            model_name='vacina',
            name='desc',
            field=models.CharField(default='Desc', max_length=100, verbose_name='Desc'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='lote',
            field=models.CharField(default='lote', max_length=100, verbose_name='lote'),
        ),
    ]
