# Generated by Django 2.2 on 2021-09-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0005_auto_20210901_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='qtd_dose',
            field=models.IntegerField(default=1, verbose_name='Qtd_dose'),
            preserve_default=False,
        ),
    ]
