# Generated by Django 2.2 on 2021-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0007_auto_20210901_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='datetime',
            field=models.DateField(auto_now=True, verbose_name='Data/Hora'),
        ),
    ]
