# Generated by Django 2.2 on 2021-10-13 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacina', '0008_vacina_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('telefone', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('endereco', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('Comorbidade', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('nome', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('email', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('cidade', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('alergia', models.CharField(max_length=100, verbose_name='Data/Hora')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
