# Generated by Django 2.2 on 2021-10-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
