# Generated by Django 2.2 on 2021-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0010_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Comorbidade',
            field=models.CharField(max_length=100, verbose_name='Possui Comorbidade?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alergia',
            field=models.CharField(max_length=100, verbose_name='Possui algum tipo de alergia?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=100, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
    ]
