# Generated by Django 2.2 on 2021-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0011_auto_20211013_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
