# Generated by Django 2.2 on 2021-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0012_auto_20211013_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='name',
        ),
        migrations.AddField(
            model_name='vacina',
            name='vacina',
            field=models.CharField(default='Vacina', max_length=100, verbose_name='Vacina'),
        ),
    ]
