# Generated by Django 2.2 on 2021-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0013_auto_20211013_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='qtd_dose',
        ),
        migrations.AddField(
            model_name='vacina',
            name='dose',
            field=models.CharField(default='Dose', max_length=100, verbose_name='Dose'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='fabricante',
            field=models.CharField(default='Fabricante', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='prof',
            field=models.CharField(default='Profissional', max_length=100, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='reg_profissional',
            field=models.CharField(default='Reg Profissional', max_length=100, verbose_name='Reg Profissional'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='unidade',
            field=models.CharField(default='Unidade', max_length=100, verbose_name='Unidade'),
        ),
    ]
