# Generated by Django 2.2 on 2021-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0014_auto_20211013_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='data_fabricacao',
            field=models.DateField(auto_now=True, verbose_name='Data_Fabricação'),
        ),
    ]
