# Generated by Django 2.2 on 2021-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0015_vacina_data_fabricacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='datetime',
        ),
        migrations.AddField(
            model_name='vacina',
            name='data_aplicacao',
            field=models.DateField(auto_now=True, verbose_name='Data Aplicação'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='data_validade',
            field=models.CharField(default='Data Validade', max_length=100, verbose_name='Data Validade'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='data_fabricacao',
            field=models.DateField(auto_now=True, verbose_name='Data Fabricação'),
        ),
    ]
