# Generated by Django 2.2 on 2021-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0018_auto_20211024_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sobrenome',
            field=models.CharField(default='Sobrenome', max_length=100, verbose_name='Sobrenome'),
        ),
    ]
