# Generated by Django 2.2 on 2021-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0019_profile_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Email', max_length=100, verbose_name='Informe seu Email'),
        ),
    ]
