# Generated by Django 2.2 on 2021-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0021_auto_20211024_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(default='Banner', max_length=100, verbose_name='Banner')),
            ],
        ),
    ]
