# Generated by Django 2.2 on 2021-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0022_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.CharField(default='Banner', max_length=200, verbose_name='Banner'),
        ),
    ]
