# Generated by Django 2.2 on 2021-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0023_auto_20211024_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.TextField(default='EM BREVE SERÁ DIVULGADO UMA NOVA CAMPANHA DE VACINAÇÃO', max_length=300, verbose_name='Banner'),
        ),
    ]
