# Generated by Django 2.2 on 2021-10-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0024_auto_20211024_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.TextField(default='EM BREVE SERÁ DIVULGADO UMA NOVA CAMPANHA DE VACINAÇÃO', max_length=1000, verbose_name='Banner'),
        ),
    ]
