# Generated by Django 2.2 on 2021-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0025_auto_20211030_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alergia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='comorbidade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
