# Generated by Django 2.2 on 2021-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0026_auto_20211111_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(default='Telefone', max_length=11, verbose_name='Telefone'),
        ),
    ]
