# Generated by Django 2.2 on 2021-11-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0027_profile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alergia',
            field=models.CharField(default='Alergia', max_length=100, verbose_name='Apresenta algum tipo de alergia?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(default='Cidade', max_length=30, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comorbidade',
            field=models.CharField(default='Comorbidade', max_length=10, verbose_name='Possui Comorbidade?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(default='Endereço', max_length=50, verbose_name='Endereço'),
        ),
    ]
