# Generated by Django 2.2 on 2021-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0029_vacina_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='data_validade',
            field=models.DateTimeField(max_length=100, verbose_name='Data Validade'),
        ),
    ]
