# Generated by Django 2.2 on 2021-11-17 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0031_auto_20211117_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='data_fabricacao',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Fabricação'),
        ),
    ]
